#!/usr/bin/expect

source ./test.exp

test_label "Should create Electrum mnemonic"

spawn qr-backup.sh --create-electrum-mnemonic

expect {
  -re {Format USB flash drive \(y or n\)\?} {
    test_send "n\r"
  }
}

expect {
  -re {\[sudo\] password for pi:} {
    test_send "$env(password)\r"
  }
}

expect {
  -re {Creating Electrum mnemonic…}
}

expect {
  -re {([a-z]+ ?){24}} {
    test_ok true
  }
}
